# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Style Guide
email: mpurdy1@utk.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://notthehill.utk.edu/" # the base hostname & protocol for your site, e.g. http://example.com
root: /
permalink: /:year/:month/:day/:title/

source: source
destination: public
plugins_dir: plugins
code_dir: downloads/code
category_dir: blog/categories
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
future: true


titlecase: true       # Converts page and post titles to titlecase


# Build settings
markdown: kramdown
kramdown:
  auto_ids:       true
  entity_output:  numeric
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

exclude:
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _sass
    style: compressed



collections:
      
  patterns:
    output: true
    permalink: /components/:slug/
